# Generated by Django 5.1.1 on 2024-09-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_published_date_post_created_at_and_more'),
    ]

    operations = [
    ]
